# Generated by Django 2.2.5 on 2020-02-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='SGroup',
        ),
    ]
