# Generated by Django 2.2.5 on 2020-03-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_auto_20200321_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlentity',
            name='deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='controlentity',
            name='mark_max',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sgroup',
            name='curator',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sgroup',
            name='representative',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='page',
            field=models.URLField(blank=True),
        ),
    ]
