# Generated by Django 2.2.5 on 2020-04-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_attendancetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetoken',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.Lesson'),
        ),
    ]
