# Generated by Django 2.2.5 on 2020-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_auto_20200422_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlentity',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='academiccourse',
            constraint=models.UniqueConstraint(fields=('discipline', 'teacher', 'group'), name='unique_courses'),
        ),
    ]
