# Generated by Django 2.2.5 on 2020-04-22 20:18

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_auto_20200422_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlentity',
            name='mark_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('reason', 'student'), name='unique_marks'),
        ),
    ]
