# Generated by Django 2.2.5 on 2020-04-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0014_auto_20200422_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.AcademicCourse')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.Teacher')),
            ],
        ),
    ]
