# Generated by Django 2.2.5 on 2020-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0017_auto_20200424_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlentity',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
