# Generated by Django 2.2.5 on 2020-04-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0018_auto_20200425_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
