# Generated by Django 2.2.5 on 2020-04-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0019_teacher_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlentity',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='controlentity',
            constraint=models.UniqueConstraint(fields=('course', 'etype', 'name'), name='unique_control'),
        ),
    ]
